### ISSUE TITLE
Erros SQL na versão SEI 4.1.3

### ISSUE THREAD

**Issue by amelquia** [pengovbr/mod-sei-pen#619]
**Descreva o erro**
 
Erros de SQL na versão SEI 4.1.3.

Erros abaixo:

sei 4.1.3 /mysql
 
Text
........EEEEE..................................................  63 / 176 ( 35%)
............................................................... 126 / 176 ( 71%)
..................................................              176 / 176 (100%)

Time: 3.26 hours, Memory: 54.00 MB

There were 5 errors:

1) MapeamentoTipoProcessoDesativarReativarTest::test_desativacao_mapeamento_orgao_externo
PHPUnit\Extensions\Selenium2TestCase\WebDriverException: element click intercepted: Element <a selected="" id="linkMenu138" style="padding-left: 75px; background: rgba(255, 255, 255, 0.2);" link="pen_map_orgaos_externos_listar" href="controlador.php?acao=pen_map_orgaos_externos_listar&infra_item_menu=138&infra_sistema=100000100&infra_unidade_atual=110000001&infra_hash=af34ffa7d4e4621d5f257492801a752a33afd3d295bec1a0950e85c6139664f6">...</a> is not clickable at point (128, 122). Other element would receive the click: <input type="text" id="txtInfraPesquisarMenu" class="infraPesquisarMenu infraText" onkeyup="infraFiltrarMenuBootstrap()" placeholder="Pesquisar no Menu" title="Pesquisar no Menu">
  (Session info: chrome=94.0.4606.61)
  (Driver info: chromedriver=94.0.4606.61 (418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}),platform=Linux 6.8.0-40-generic x86_64)

/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Driver.php:168
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Driver.php:178
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/CommandsHolder.php:105
/tests/src/paginas/PaginaTramiteMapeamentoOrgaoExterno.php:18
/tests/tests/MapeamentoTipoProcessoDesativarReativarTest.php:55
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:395
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:360
phpvfscomposer:///tests/vendor/phpunit/phpunit/phpunit:97

2) MapeamentoTipoProcessoDesativarReativarTest::test_reativacao_mapeamento_orgao_externo
PHPUnit\Extensions\Selenium2TestCase\WebDriverException: element click intercepted: Element <a selected="" id="linkMenu138" style="padding-left: 75px; background: rgba(255, 255, 255, 0.2);" link="pen_map_orgaos_externos_listar" href="controlador.php?acao=pen_map_orgaos_externos_listar&infra_item_menu=138&infra_sistema=100000100&infra_unidade_atual=110000001&infra_hash=ce66edc86a3b9e508c80ac03746bedc6f5f7ad22238f79f17e11cd89cf4400cf">...</a> is not clickable at point (128, 122). Other element would receive the click: <input type="text" id="txtInfraPesquisarMenu" class="infraPesquisarMenu infraText" onkeyup="infraFiltrarMenuBootstrap()" placeholder="Pesquisar no Menu" title="Pesquisar no Menu">
  (Session info: chrome=94.0.4606.61)
  (Driver info: chromedriver=94.0.4606.61 (418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}),platform=Linux 6.8.0-40-generic x86_64)

/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Driver.php:168
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Driver.php:178
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/CommandsHolder.php:105
/tests/src/paginas/PaginaTramiteMapeamentoOrgaoExterno.php:18
/tests/tests/MapeamentoTipoProcessoDesativarReativarTest.php:84
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:395
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:360
phpvfscomposer:///tests/vendor/phpunit/phpunit/phpunit:97

3) MapeamentoTipoProcessoDesativarReativarTest::test_desativacao_checkbox_mapeamento_orgao_externo
PHPUnit\Extensions\Selenium2TestCase\WebDriverException: element click intercepted: Element <a selected="" id="linkMenu138" style="padding-left: 75px; background: rgba(255, 255, 255, 0.2);" link="pen_map_orgaos_externos_listar" href="controlador.php?acao=pen_map_orgaos_externos_listar&infra_item_menu=138&infra_sistema=100000100&infra_unidade_atual=110000001&infra_hash=18b86de56f73cd260b6ad46a9d84983e9e444fcf8431311d531ef12751fac3e6">...</a> is not clickable at point (128, 122). Other element would receive the click: <input type="text" id="txtInfraPesquisarMenu" class="infraPesquisarMenu infraText" onkeyup="infraFiltrarMenuBootstrap()" placeholder="Pesquisar no Menu" title="Pesquisar no Menu">
  (Session info: chrome=94.0.4606.61)
  (Driver info: chromedriver=94.0.4606.61 (418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}),platform=Linux 6.8.0-40-generic x86_64)

/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Driver.php:168
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Driver.php:178
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/CommandsHolder.php:105
/tests/src/paginas/PaginaTramiteMapeamentoOrgaoExterno.php:18
/tests/tests/MapeamentoTipoProcessoDesativarReativarTest.php:113
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:395
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:360
phpvfscomposer:///tests/vendor/phpunit/phpunit/phpunit:97

4) MapeamentoTipoProcessoDesativarReativarTest::test_reativar_checkbox_mapeamento_orgao_externo
PHPUnit\Extensions\Selenium2TestCase\WebDriverException: element click intercepted: Element <a selected="" id="linkMenu138" style="padding-left: 75px; background: rgba(255, 255, 255, 0.2);" link="pen_map_orgaos_externos_listar" href="controlador.php?acao=pen_map_orgaos_externos_listar&infra_item_menu=138&infra_sistema=100000100&infra_unidade_atual=110000001&infra_hash=8b1c8e2ab79a48f95a0607215b013cd0c3237849e9164d22ac4edcf8be517a8d">...</a> is not clickable at point (128, 122). Other element would receive the click: <input type="text" id="txtInfraPesquisarMenu" class="infraPesquisarMenu infraText" onkeyup="infraFiltrarMenuBootstrap()" placeholder="Pesquisar no Menu" title="Pesquisar no Menu">
  (Session info: chrome=94.0.4606.61)
  (Driver info: chromedriver=94.0.4606.61 (418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}),platform=Linux 6.8.0-40-generic x86_64)

/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Driver.php:168
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Driver.php:178
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/CommandsHolder.php:105
/tests/src/paginas/PaginaTramiteMapeamentoOrgaoExterno.php:18
/tests/tests/MapeamentoTipoProcessoDesativarReativarTest.php:142
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:395
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:360
phpvfscomposer:///tests/vendor/phpunit/phpunit/phpunit:97

5) MapeamentoTipoProcessoExcluirTest::test_excluir_mapeamento_orgao_externo
PHPUnit\Extensions\Selenium2TestCase\WebDriverException: element click intercepted: Element <a selected="" id="linkMenu138" style="padding-left: 75px; background: rgba(255, 255, 255, 0.2);" link="pen_map_orgaos_externos_listar" href="controlador.php?acao=pen_map_orgaos_externos_listar&infra_item_menu=138&infra_sistema=100000100&infra_unidade_atual=110000001&infra_hash=18a0e3c8bb2d8c541ab3f5a56a346ea411f246a464b9deb959e0ede2ddb86d4f">...</a> is not clickable at point (128, 122). Other element would receive the click: <input type="text" id="txtInfraPesquisarMenu" class="infraPesquisarMenu infraText" onkeyup="infraFiltrarMenuBootstrap()" placeholder="Pesquisar no Menu" title="Pesquisar no Menu">
  (Session info: chrome=94.0.4606.61)
  (Driver info: chromedriver=94.0.4606.61 (418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}),platform=Linux 6.8.0-40-generic x86_64)

/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Driver.php:168
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Driver.php:178
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/CommandsHolder.php:105
/tests/src/paginas/PaginaTramiteMapeamentoOrgaoExterno.php:18
/tests/tests/MapeamentoTipoProcessoExcluirTest.php:59
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:395
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:360
phpvfscomposer:///tests/vendor/phpunit/phpunit/phpunit:97

ERRORS!
Tests: 176, Assertions: 1697, Errors: 5.
ERROR: 2
make: *** [Makefile:195: test-functional] Error 2

-----

**Para reproduzir**
Passos para reproduzir o comportamento:
1. Vá para '...'
2. Clique em '....'
3. Role para baixo até '....'
4. Veja o erro

-----

**Comportamento esperado**
Uma descrição clara e concisa do que você esperava que acontecesse.

-----

**Screenshots**
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema. Sugerimos o uso do Peek (linux) ou ScreenToGif (windows) para captura.

-----

**Contexto da falha (Por favor, complete a seguinte informação):**
 - Versão do sistema: [ex: 1.0.1]
 - Navegador: [ex. chrome, safari]
 - Perfil do Usuário: [ex: colaborador, externo, coordenador, administrador, etc.]
 - Banco de dados: [MySQL, SQLServer, Oracle ou PostgreSQL]
-----

**Informações adicionais**
Adicione qualquer outro contexto sobre o problema aqui.

-----
**Log de Erros**
Adicione o log de erros registrado pelo sistema. Verifique o log registrado no servidor, através da funcionalidade Infra> Log

**Comment by mateussbh** [comment]
Erros executados no sei413/oracle:

`........EEEEE...............................................ES.  63 / 176 ( 35%)
...F.............................ES............................ 126 / 176 ( 71%)
..................................................              176 / 176 (100%)

Time: 3.59 hours, Memory: 56.00 MB

There were 7 errors:

1) MapeamentoTipoProcessoDesativarReativarTest::test_desativacao_mapeamento_orgao_externo
PHPUnit\Extensions\Selenium2TestCase\WebDriverException: element click intercepted: Element <a selected="" id="linkMenu137" style="padding-left: 75px; background: rgba(255, 255, 255, 0.2);" link="pen_map_orgaos_externos_listar" href="controlador.php?acao=pen_map_orgaos_externos_listar&amp;infra_item_menu=137&amp;infra_sistema=100000100&amp;infra_unidade_atual=110000001&amp;infra_hash=489ab47f7a0bc7eeef8634ebce9e749ce3c9707f588ca9d4369b9153dc4a63a7">...</a> is not clickable at point (128, 122). Other element would receive the click: <input type="text" id="txtInfraPesquisarMenu" class="infraPesquisarMenu infraText" onkeyup="infraFiltrarMenuBootstrap()" placeholder="Pesquisar no Menu" title="Pesquisar no Menu">
  (Session info: chrome=94.0.4606.61)
  (Driver info: chromedriver=94.0.4606.61 (418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}),platform=Linux 6.8.0-40-generic x86_64)

/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Driver.php:168
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Driver.php:178
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/CommandsHolder.php:105
/tests/src/paginas/PaginaTramiteMapeamentoOrgaoExterno.php:18
/tests/tests/MapeamentoTipoProcessoDesativarReativarTest.php:55
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:395
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:360
phpvfscomposer:///tests/vendor/phpunit/phpunit/phpunit:97

2) MapeamentoTipoProcessoDesativarReativarTest::test_reativacao_mapeamento_orgao_externo
PHPUnit\Extensions\Selenium2TestCase\WebDriverException: element click intercepted: Element <a selected="" id="linkMenu137" style="padding-left: 75px; background: rgba(255, 255, 255, 0.2);" link="pen_map_orgaos_externos_listar" href="controlador.php?acao=pen_map_orgaos_externos_listar&amp;infra_item_menu=137&amp;infra_sistema=100000100&amp;infra_unidade_atual=110000001&amp;infra_hash=4972df00a4930d84a00bd1c94f58362a6c5d0f9c07cba76ff0340e2bd96fc63b">...</a> is not clickable at point (128, 122). Other element would receive the click: <input type="text" id="txtInfraPesquisarMenu" class="infraPesquisarMenu infraText" onkeyup="infraFiltrarMenuBootstrap()" placeholder="Pesquisar no Menu" title="Pesquisar no Menu">
  (Session info: chrome=94.0.4606.61)
  (Driver info: chromedriver=94.0.4606.61 (418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}),platform=Linux 6.8.0-40-generic x86_64)

/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Driver.php:168
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Driver.php:178
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/CommandsHolder.php:105
/tests/src/paginas/PaginaTramiteMapeamentoOrgaoExterno.php:18
/tests/tests/MapeamentoTipoProcessoDesativarReativarTest.php:84
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:395
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:360
phpvfscomposer:///tests/vendor/phpunit/phpunit/phpunit:97

3) MapeamentoTipoProcessoDesativarReativarTest::test_desativacao_checkbox_mapeamento_orgao_externo
PHPUnit\Extensions\Selenium2TestCase\WebDriverException: element click intercepted: Element <a selected="" id="linkMenu137" style="padding-left: 75px; background: rgba(255, 255, 255, 0.2);" link="pen_map_orgaos_externos_listar" href="controlador.php?acao=pen_map_orgaos_externos_listar&amp;infra_item_menu=137&amp;infra_sistema=100000100&amp;infra_unidade_atual=110000001&amp;infra_hash=bcb93375957d301298073f53993b75764df97ce81d48ea166f423a06a856a9d1">...</a> is not clickable at point (128, 122). Other element would receive the click: <input type="text" id="txtInfraPesquisarMenu" class="infraPesquisarMenu infraText" onkeyup="infraFiltrarMenuBootstrap()" placeholder="Pesquisar no Menu" title="Pesquisar no Menu">
  (Session info: chrome=94.0.4606.61)
  (Driver info: chromedriver=94.0.4606.61 (418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}),platform=Linux 6.8.0-40-generic x86_64)

/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Driver.php:168
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Driver.php:178
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/CommandsHolder.php:105
/tests/src/paginas/PaginaTramiteMapeamentoOrgaoExterno.php:18
/tests/tests/MapeamentoTipoProcessoDesativarReativarTest.php:113
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:395
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:360
phpvfscomposer:///tests/vendor/phpunit/phpunit/phpunit:97

4) MapeamentoTipoProcessoDesativarReativarTest::test_reativar_checkbox_mapeamento_orgao_externo
PHPUnit\Extensions\Selenium2TestCase\WebDriverException: element click intercepted: Element <a selected="" id="linkMenu137" style="padding-left: 75px; background: rgba(255, 255, 255, 0.2);" link="pen_map_orgaos_externos_listar" href="controlador.php?acao=pen_map_orgaos_externos_listar&amp;infra_item_menu=137&amp;infra_sistema=100000100&amp;infra_unidade_atual=110000001&amp;infra_hash=94006bec47d1285edf2d334ac5118397621ecaebc9656508abb5dc0d5ce9b95e">...</a> is not clickable at point (128, 122). Other element would receive the click: <input type="text" id="txtInfraPesquisarMenu" class="infraPesquisarMenu infraText" onkeyup="infraFiltrarMenuBootstrap()" placeholder="Pesquisar no Menu" title="Pesquisar no Menu">
  (Session info: chrome=94.0.4606.61)
  (Driver info: chromedriver=94.0.4606.61 (418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}),platform=Linux 6.8.0-40-generic x86_64)

/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Driver.php:168
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Driver.php:178
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/CommandsHolder.php:105
/tests/src/paginas/PaginaTramiteMapeamentoOrgaoExterno.php:18
/tests/tests/MapeamentoTipoProcessoDesativarReativarTest.php:142
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:395
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:360
phpvfscomposer:///tests/vendor/phpunit/phpunit/phpunit:97

5) MapeamentoTipoProcessoExcluirTest::test_excluir_mapeamento_orgao_externo
PHPUnit\Extensions\Selenium2TestCase\WebDriverException: element click intercepted: Element <a selected="" id="linkMenu137" style="padding-left: 75px; background: rgba(255, 255, 255, 0.2);" link="pen_map_orgaos_externos_listar" href="controlador.php?acao=pen_map_orgaos_externos_listar&amp;infra_item_menu=137&amp;infra_sistema=100000100&amp;infra_unidade_atual=110000001&amp;infra_hash=a9bb3dc0753f159744f8b50a5e901df00a6b4a7c56b28f9cca41be54e512b09a">...</a> is not clickable at point (128, 122). Other element would receive the click: <input type="text" id="txtInfraPesquisarMenu" class="infraPesquisarMenu infraText" onkeyup="infraFiltrarMenuBootstrap()" placeholder="Pesquisar no Menu" title="Pesquisar no Menu">
  (Session info: chrome=94.0.4606.61)
  (Driver info: chromedriver=94.0.4606.61 (418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}),platform=Linux 6.8.0-40-generic x86_64)

/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Driver.php:168
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Driver.php:178
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/CommandsHolder.php:105
/tests/src/paginas/PaginaTramiteMapeamentoOrgaoExterno.php:18
/tests/tests/MapeamentoTipoProcessoExcluirTest.php:59
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:395
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:360
phpvfscomposer:///tests/vendor/phpunit/phpunit/phpunit:97

6) TramiteProcessoComDevolucaoAnexadoOutroTest::test_verificar_devolucao_origem_processo_anexado
PHPUnit\Extensions\Selenium2TestCase\WebDriverException: Timed out after 360 seconds

/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/WaitUntil.php:138
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:597
/tests/tests/TramiteProcessoComDevolucaoAnexadoOutroTest.php:157
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:395
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:360
phpvfscomposer:///tests/vendor/phpunit/phpunit/phpunit:97

Caused by
PHPUnit\Framework\ExpectationFailedException: Failed asserting that true is false.

/tests/tests/TramiteProcessoComDevolucaoAnexadoOutroTest.php:154
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/WaitUntil.php:119
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:597
/tests/tests/TramiteProcessoComDevolucaoAnexadoOutroTest.php:157
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:395
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:360
phpvfscomposer:///tests/vendor/phpunit/phpunit/phpunit:97

7) TramiteProcessoContendoDocumentoExternoMesmoOrgaoTest::test_verificar_origem_processo_contendo_documento_gerado
PHPUnit\Extensions\Selenium2TestCase\WebDriverException: no such element: Unable to locate element: {"method":"link text","selector":"99990.000080/2024-00"}
  (Session info: chrome=94.0.4606.61)
  (Driver info: chromedriver=94.0.4606.61 (418b78f5838ed0b1c69bb4e51ea0252171854915-refs/branch-heads/4606@{#1204}),platform=Linux 6.8.0-40-generic x86_64)

/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Driver.php:168
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/CommandsHolder.php:113
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Element/Accessor.php:140
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Element/Accessor.php:178
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase/Element/Accessor.php:96
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:440
/tests/src/paginas/PaginaControleProcesso.php:95
/tests/tests/CenarioBaseTestCase.php:290
/tests/tests/TramiteProcessoContendoDocumentoExternoMesmoOrgaoTest.php:50
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:395
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:360
phpvfscomposer:///tests/vendor/phpunit/phpunit/phpunit:97

--

There was 1 failure:

1) TramiteProcessoComDevolucaoContendoOutroAnexadoTest::test_verificar_devolucao_destino_processo_anexado
Failed asserting that 3 matches expected 4.

/tests/tests/TramiteProcessoComDevolucaoContendoOutroAnexadoTest.php:185
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:395
/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:360
phpvfscomposer:///tests/vendor/phpunit/phpunit/phpunit:97

--

There were 2 skipped tests:

1) TramiteProcessoComDevolucaoAnexadoOutroTest::test_verificar_devolucao_destino_processo_anexado
This test depends on "TramiteProcessoComDevolucaoAnexadoOutroTest::test_verificar_devolucao_origem_processo_anexado" to pass.

/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:360
phpvfscomposer:///tests/vendor/phpunit/phpunit/phpunit:97

2) TramiteProcessoContendoDocumentoExternoMesmoOrgaoTest::test_verificar_destino_processo_contendo_documento_gerado
This test depends on "TramiteProcessoContendoDocumentoExternoMesmoOrgaoTest::test_verificar_origem_processo_contendo_documento_gerado" to pass.

/tests/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:360
phpvfscomposer:///tests/vendor/phpunit/phpunit/phpunit:97

ERRORS!
Tests: 176, Assertions: 1709, Errors: 7, Failures: 1, Skipped: 2.
make: *** [Makefile:195: test-functional] Error 2
`
